# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
      - '1.18-master'    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.16
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission buildscripts
      run: |
        chmod +x ./etc/buildscripts/1182build |
        chmod +x ./etc/buildscripts/upload |
        chmod +x ./gradlew
    - name: Build 1.16.5
      run: ./etc/buildscripts/1182build
    - name: Cleanup
      run: git reset --hard HEAD
    - name: Publish to Discord
      env: # Setup Webhook Thing
        DEVEL_WEBHOOK_URL: ${{ secrets.DEVEL_WEBHOOK_URL }}
      run: ./etc/buildscripts/upload
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: 1182-devel
        path: build/libs/*








